project:
  type: website
  output-dir: docs

website:
  title: "Zihui Yao"
  navbar:
    left:
      - href: index.qmd
        text: Zihui Yao
      - href: projects.qmd
        text: Work
      - href: about.qmd
        text: Profile
    right:
      - text: Resume
        href: assets/Zihui_Yao_Resume.pdf
      - icon: github
        href: https://github.com/rsm-ziyao
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/zihui-yao-2223853ab/
        aria-label: LinkedIn
      - icon: envelope
        href: mailto:ziyao@ucsd.edu
        aria-label: Email

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
